[build]
builder = "nixpacks"

[deploy]
startCommand = "python3 railway_optimized_server.py"
healthcheckPath = "/health"
healthcheckTimeout = 60
restartPolicyType = "on_failure"

[variables]
PORT = "5000"
NIXPACKS_PYTHON_VERSION = "3.11"